Repository openrewrite/rewrite-jackson, pull requests merged in 2024-10, with the labels that each got.

#13 Remove doubly annotated codehaus annotations
  src/main/java/org/openrewrite/java/jackson/codehaus/RemoveDoublyAnnotatedCodehausAnnotations.java
  src/main/resources/META-INF/rewrite/codehaus-to-fasterxml.yml
  src/test/java/org/openrewrite/java/jackson/codehaus/RemoveDoublyAnnotatedCodehausAnnotationsTest.java
Labels: enhancement, recipe

#14 Only `RemoveDoublyAnnotatedCodehausAnnotations` from the same element; not any element in the same class
  src/main/java/org/openrewrite/java/jackson/codehaus/RemoveDoublyAnnotatedCodehausAnnotations.java
  src/test/java/org/openrewrite/java/jackson/codehaus/RemoveDoublyAnnotatedCodehausAnnotationsTest.java
Labels: bug

#16 Add transfers for using arguments
  src/main/java/org/openrewrite/java/jackson/codehaus/RemoveDoublyAnnotatedCodehausAnnotations.java
  src/main/java/org/openrewrite/java/jackson/codehaus/TransferJsonSerializeArgumentsFromCodehausToFasterXML.java
  src/main/resources/META-INF/rewrite/codehaus-to-fasterxml.yml
  src/test/java/org/openrewrite/java/jackson/codehaus/TransferJsonSerializeArgumentsFromCodehausToFasterXMLTest.java
Labels: enhancement
